### ISSUE TITLE
@include background-grid throwing error on using with codekit

### ISSUE THREAD

**Issue by iaakash** [at-import/Singularity#106]
Hello I'm New to Singularity and just tried out the demo code to construct few grids but it seems that @include background-grid is not working as it should and throws this error.

Here is the show: https://www.evernote.com/shard/s157/sh/aca00cf3-fe5e-4631-a0c7-1b21aa4d7c5b/a4689fef4f54f39b54b016a6bbe1d3b4
## 

Thanks
Aakash

**Comment by Snugug** [comment]
Have your set your grids and gutters? Do you have an isolated case of where this happens in code?

**Comment by iaakash** [comment]
Thanks for getting back to me. Dropping you a short snippet of my scss file which produced this.

@import "partials/singularitygs";

$grids: 1 1 1 1;
//$gutters: 1/3;

.container {@include background-grid; max-width:960px;border:1px solid red;
min-height: 100%; margin: 0 auto;}
body,html {background: grey; height: 100%; padding: 0; margin: 0;}

Now above if i replace 1 1 1 1 with any single value like 2 or 4 or 6, it works perfect but as soon as that value increases, it shows me the above stated error. This code is same as shown in video walkthrough.

**Comment by Snugug** [comment]
This appears to be an issue with CodeKit as it works fine with command line compiling. Going to see if I can find a solution for it, but it is not an issue w/Singularity.

**Comment by Snugug** [comment]
I've determined the problem, and it's a strage issue. The issue is that CodeKit, even when using the system gems, doesn't seem to be able to use SassScript, which is needed for asymmetric grids to function. This issue is not a Singularity issue, but rather a CodeKit issue. The underlying issue can be tracked in [CodeKit Issue 608](https://github.com/bdkjones/CodeKit/issues/608).
