### ISSUE TITLE
$mobile-first variable not working as expected

### ISSUE THREAD

**Issue by jahvi** [at-import/Singularity#111]
I'm setting `$mobile-first: false;` on my stylesheets however the compiled breakpoints are still redering using `min-width` instead of `max-width`

This might be related to #108, maybe since the variable isn't set as `!default` it could be getting overwritten.

**Comment by Snugug** [comment]
This is not related. If you're building desktop-first are are using single numbers for your media queries, you need to set [`$breakpoint-default-feature: max-width`](https://github.com/Team-Sass/breakpoint/wiki/Basic-Media-Queries#default-single-and-pair) in order to have Breakpoint write `max-width` media queries as their default feature. Unfortunately, until there are more robust tools available to Sass, we can't do the automatic conversion for you (nor should we, as you may want that default feature to be anything)

**Comment by Snugug** [comment]
I will add this to the documentation though.

UPDATE:

[Updated the docs](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#responsive-grids)

**Comment by jahvi** [comment]
Thanks for the clarification, I thought the `$mobile-first` variable made that change when set to true
