### ISSUE TITLE
column based float layout error (nth-child)

### ISSUE THREAD

**Issue by chrisspiegl** [at-import/Singularity#145]
I wonder if there is a way to do something like the following: http://sassmeister.com/gist/7316357

At a window size less than 600px it shows correct. But for larger than 600px it is not correct. The error is based on the fact that the `&:nth-child(3n)` from the 'mobile-layout' still is there even if the screen size is larger than 600px. The only way to revert that would be to either base both in media queries (`@include breakpoint(0px)` or to add a reset `&:nth-child(3n)` to the 600px breakpoint.

My question: is there a singularity way of doing this nicely? If not would this be something to add to singularity core?

**Comment by lolmaus** [comment]
Your problem is that on wide screens both 3-column and 5-column spanning is applied at the same time.

You should put your small screen spans into a media query too: http://sassmeister.com/gist/7317627

Also, you don't need to span containers (you even override it with `width: 100%`).

I would also suggest some refactoring both in Sass and HTML. Tell me if you're interested.

Please note that Team-Sass policy is that you should ask for support with Singularity and Breakpoint on [Stack Overflow](http://stackoverflow.com/) rather than in Github issue queue.

**Comment by chrisspiegl** [comment]
Ok, I thought something like that. Just was curios if there is a better way and maybe a feature to be added. Looks like a little workaround fix.

Anyways: thanks and closed.
