### ISSUE TITLE
Ratio Grid Option

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#15]
Like @canarymason had suggested, it would be awesome to have a simple way of creating ratio based grids, and I think Singularity is basically all set up to do this already, sans the actual math behind it (which I think I've figured out!)

Singularity currently supports floating point grid items as well as integers, and we'd need these in order to effectively create ratio grids. The syntax for ratio would be fairly simple as I see it:

``` scss
ratio($ratio, $steps, $order: 'increase')
```

I'm currently experimenting to see if my math is right, and if it is, and you're interested in including it, happy to post it here/issue a pull request.

**Comment by Snugug** [comment]
As an aside, this is going to need Sassy Math for exponents.

**Comment by scottkellum** [comment]
Awesome, am planning on breaking these functions into a separate folder of grid plugins at some point.

There are a number of options we might want to add here. A simple logarithmic plugin to a modular scale gives one kind of result `$columns: ms(1), ms(2), ms(3), ms(4)` but because Singularity calculates these relative to each other, it might be advantageous to offset that with a Fibonacci scale `$columns: ms(1), ms(1), ms(2), ms(3), ms(5), ms(8)`. This results in columns with a ratio more true to the context.

Also, if you look at a grid based on the Fibonacci spiral, it writes grids like this: `$columns: ms(3), ms(5), ms(5), ms(1)`. That sequence probably needs some work, but some crazy shit.

As soon as modular-scale v1.0 is released Sassy Math will be included with that and Singularity.

Once we reorganize so that plug-in functions like this have a dedicated folder I hope to grow more functions like this. It will also be like an API for any developer to plug into Singularity.

**Comment by scottkellum** [comment]
Note, this doesn’t need to be wrapped up into one function. Probably easier/more user friendly to write a different function for each kind of sequence.

**Comment by Snugug** [comment]
Agreed. General ratios is easy to do, something like logs or Fibonacci would be better off in other functions.
