### ISSUE TITLE
Not aligning up with BG grid

### ISSUE THREAD

**Issue by stoplion** [at-import/Singularity#156]
![image](https://f.cloud.github.com/assets/231343/1750811/fb7869ea-65b5-11e3-88ba-8de7a69da53f.png)

$grids: 12
$gutters: 2/3
$output: 'isolation'
# container

```
+background-grid
margin: 0 auto
```
# container .section__wrapper

```
+grid-span(10, 2)
background: red
```

Noticed the last column in the background grid. It looks like a third is getting truncated off the screen.
I  measured the left and right edges (or red block) and they both measure equally. 

Here is a shot without the red block.
![image](https://f.cloud.github.com/assets/231343/1750813/974a11fc-65b6-11e3-900d-7fbff6e625c3.png)
All columns measure 76px, but the last one measures 71px.

**Comment by lolmaus** [comment]
The grid background is not accurate because browsers draw linear gradients inaccurately. Rounding errors tend to accumulate towards the right side.

This is a known issue, but Singularity authors can not do anything about it.

Note that the spanning of the grid elements is also inaccurate and not appropriate for pixel-perfect markup, though it is less inaccurate than gradients. Isolation technique aims to reduce the error to lowest possible minimum.

**Comment by Snugug** [comment]
As @lolmaus said, this is a browser rounding issue and is a [documented known issue](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#grid-backgrounds-may-be-inaccurate) that is beyond our ability to solve.

**Comment by stoplion** [comment]
Ok
