### ISSUE TITLE
Push/Pull Documentation

### ISSUE THREAD

**Issue by equivalentideas** [at-import/Singularity#161]
Would be good to add documentation of the _push/pull_ functions required to use the _floats output method_. There should also be a link to this documentation on the [Outputs page](https://github.com/Team-Sass/Singularity/wiki/Output-Styles). At the moment it's a bit tricky to find an explanation of how the push and pull works.

Thanks for this mind blowing tool!

**Comment by lolmaus** [comment]
Not trying argue against the suggestion to update the documentation, but the other method allows positioning a block into any column, so push/pull are completely unnecessary.

**Comment by lolmaus** [comment]
Also, that's a wiki page, you could just update it yourself.

**Comment by equivalentideas** [comment]
Unfortunately I don't grok all the arguments in the function :D

Should I make the section for someone else to fill?

**Comment by lolmaus** [comment]
I misread your question (i thought you were only suggesting to mention that the push/pull helpers are only necessary for float spanning).

Also, i proceeded to add documentation to the wiki and discovered that it's forbidden for non-maintainers to edit the wiki.

In case you're still struggling with the helpers, here's a quick insight into how they work.

The `push-float` helper adds extra space to the left of the block, effectively moving the block (and all the following blocks) to the right.

The `push-float` adds a negative margin, moving the block and all the following blocks to the left.

You can use these helpers to swap two blocks. Note that using `pull-float` without `push-float` will most probably result in two blocks overlapping.

The helpers take up two four arguments, with first two being mandatory.

The first argument is how many columns you would like to move the block.
The second argument is only necessary for asymmetric grids. With a symmetric grid, just set it to 1. With an asymmetric grid, set it to the number of the target column.
The third and fourth arguments are used to override grid and gutter contexts.

Note that when swapping two adjacent blocks, the first argument in `pull-float` must be larger by 1 than in `push-float`. That's because `push-float` shifts both the first and the second blocks. When you apply `pull-float(1,...)` to the second block, it will return to its original position and overlap with the second pushed block. For the second block to occupy the first block's original position, `pull-float(2,...)` must be used.

Demo: http://sassbin.com/gist/8278858/

**Comment by equivalentideas** [comment]
That's great @lolmaus , extremely helpful! How can we get this into the wiki? Should it go on the [Grid Helpers](https://github.com/Team-Sass/Singularity/wiki/Grid-Helpers) page?

Also, I'm using the functions as:

```
@include push(2,1,6)
```

—without the float (e.i. `push-float`), which I found in [demo-float.scss](https://github.com/Team-Sass/Singularity/blob/1.x.x/templates/demos/demo-float.scss) in the demos templates.. Works no worries.

**Comment by Snugug** [comment]
Don't get too attached to push/pull. We are planning in deprecating them soon in favor of simply using the isolation method as we find most of our users do that as it's much easier.

**Comment by equivalentideas** [comment]
Ok thanks. I might try and help contribute to parts of the documentation if that's helpful.

**Comment by windtrader** [comment]
Announcing the deprecation of push and pull, along with updated sgs-demo showing recommended isolation method and documentation will be great. Save much time rooting around trying to figure out intent, definition, and use of them as used in the samples. Thanks

**Comment by Snugug** [comment]
The documentation will be updated (and a new demo video will be made) once Singularity 1.2.0 is released out of RC.

**Comment by lolmaus** [comment]
A little bit offtopic:

Will you keep documentation for Singularity 1.1 available (rather than overwrite it with 1.2)? Sass 3.3 and Compass 1.0 don't seem to be released soon, so a lot of people may be stuck with Singularity 1.1.

Legacy documentation is also desirable when maintaining existing projects.

**Comment by Snugug** [comment]
Documentation related to new features will be marked as updates, not overriding.

**Comment by windtrader** [comment]
So for now, before Singularity 1.2.0 is released, is there options based on isolation to do a gutter shift adjustment like push/pull?

**Comment by Snugug** [comment]
It's "built in". Just span with the location you want, it will be put in the correct position.

**Comment by scottkellum** [comment]
There is absolutely zero need for push and pull in isolation method which has been the default mode of Singularity since it was launched. All videos and documentation reflect this currently and will not change much as a result.

**Comment by windtrader** [comment]
Seems like the only thing to do is to remove the push/pull code from the sample and that will stop questions coming from that reference. One other suggestion would be to add an example in the isolation sample showing the syntax to include a gutter in the span. Looking at the isolation sample at all widths only show content aligning within a grid or spanning grids not not including a gutter to add width to the content nor showing any content shifting over a gutter.

**Comment by equivalentideas** [comment]
May be a stupid question, but... If the float method is being removed, how can you set the width of an object, but have it fall into a column based on other objects? This seems necessary in a situation where you cant know which column it should be in, because you don't know how many objects there will be?

**Comment by Snugug** [comment]
We are not deprecating the float output style, we are deprecating the push/pull mixins. We strongly believe that you should use the output style that makes sense for the output you're trying to achieve, including mixing output styles in the same project if needed.

Something like a listing of items all the same size works well for float output, but something where you need exact control over where each column lives w/o regard to actual source order, isolation is your output style.

**Comment by equivalentideas** [comment]
This is exactly how we've been using it, that's very reassuring :) I'd be happy to write a short explanation of this for the documentation if it's welcome. I think it might help clear things up.

**Comment by Snugug** [comment]
Push/Pull has now officially been deprecated, closing this.
