### ISSUE TITLE
1.1.2: weird float-span behavior on SassMeister

### ISSUE THREAD

**Issue by lolmaus** [at-import/Singularity#163]
Float-span would not set right margin.

See this demo on SassMeister: http://sassmeister.com/gist/8536477

The weird thing is that the same code behaves correctly on SassBin: http://sassbin.com/gist/8536876/

They use the same versions of Singularity (1.1.2), though other gems are outdated on SassBin: [Gemfile.lock](https://github.com/lolmaus/sassbin/blob/1.x/Gemfile.lock) (i abandoned SassBin when SassMeister introduced HTML support).

I wonder what the reason might be.

**Comment by Snugug** [comment]
I believe this is related to #139 which has since been resolved. Can you check to see if this still is the case with Singularity 1.2.0

**Comment by lolmaus** [comment]
Yes, the problem is gone in 1.2.0.rc.3 (+ Sass 3.3.0.rc.2).

**Comment by lolmaus** [comment]
Is this going to be fixed in the 1.1.x branch?

**Comment by Snugug** [comment]
There is no 1.1.x branch.

**Comment by lolmaus** [comment]
Well, i'm not going to use Singularity 1.2 until Sass 3.3 and Compass 1 are stable. I think there are a lot of people like me.

Do we all have bear with this bug?

**Comment by Snugug** [comment]
Yes. The bug only affects float output style for spans that don't touch the first or last column and can be resolved easily by adding `margin-right: gutter-span()` to columns missing their gutters.

If you don't want to use (the perfectly stable) release candidates of Sass 3.3 and Compass 1.0 in order to utilize Singularity 1.2, you also have the option to override the `output-float` mixin and add this in to its correct spot or override the `float-span` mixin to do the same.
