### ISSUE TITLE
Grid-span help

### ISSUE THREAD

**Issue by banDeveloper** [at-import/Singularity#180]
Hello,

I have a small issue with singularitygs. I'd like to create a grid like in the 2nd image, what I'm getting instead is a grid like in the 1st image. There's several rows like this, the code is:

```
p1 {
       @include grid-span(9,1, $output-style: 'float');
    clear:both;
    @include float-span(9, 'first');
}
img {
       @include grid-span(3, 10, $output-style: 'float');
}
p2 {
       @include grid-span(9,1, $output-style: 'float');
    clear:both;
    @include float-span(9, 'first');
}
```

What am I doing wrong?

![1](https://cloud.githubusercontent.com/assets/6033149/2827569/05e02a1a-cf85-11e3-9115-c7cc09868b10.jpg)
![2](https://cloud.githubusercontent.com/assets/6033149/2827570/0866d928-cf85-11e3-9939-1dcdf9014830.jpg)

Thank you for the help!

**Comment by lolmaus** [comment]
Try applying `clear: left;` instead of `clear: both;` to `p2`.

As per [Getting Help Guidelines](https://github.com/Team-Sass/Singularity#getting-help-with-singularity), please file questions on Stack Overflow and tag it with `singularitygs`, instead of reporting them into the issue queue.

Also, provide http://sassmeister.com minimal demonstrations of your issues.
