### ISSUE TITLE
fixed gutter incompatible with background grid

### ISSUE THREAD

**Issue by daveerwin** [at-import/Singularity#187]
using version 1.2.1 
when using fixed grid and bg grid is on I get error
(Line 201 of _background-grid.scss: Incompatible units: 'px' and '%'.)

**Comment by sepal** [comment]
You need to set the gutter style to fixed in order to get rid of this message:

```
@include sgs-change('gutter styles', 'fixed');
```

**Comment by finteractive** [comment]
I too and running into this error when using the following. I tried 1.2.1, and 1.2.3. 

```
// settings.scss
@include add-grid(6);
@include add-gutter-style('split');
@include add-gutter(1em);
// Must enable debug setting
@include sgs-change('debug', true);

// style.scss
main {
  @include grid-span(6);
  @include background-grid();

```

When I replace the @include add-gutter-style('split'); with @include sgs-change('gutter styles', 'fixed');

I get this error....

WARNING: DEPRECATION: In order to remove global variable naming conflicts, Singularity's settings have been moved into the single `$singularity` variable. Please refer to our documentation (https://github.com/Team-Sass/Singularity/wiki) on how to update your settings. In the next version of Singularity, this warning will be removed. fixed has been returned.
         on line 38 of /_work/PGA_pgalinks.com/_website/sites/all/themes/pga/.vendor/bundle/ruby/2.0.0/gems/singularitygs-1.2.3/stylesheets/singularitygs/helpers/_find.scss, in `grid-span'

I recently updated compass from alpha to compass (1.0.0.rc.1) but even with the older versions on sassmeister I can't get it working...

http://sassmeister.com/gist/fd27c86808899a8e5f64

**Comment by Vagelis-Prokopiou** [comment]
I have the same problem in a libsass workflow.
If I declare <code>@include sgs-change('gutter styles', 'fixed' 'split');</code> I get the following output at the terminal multiple times and it does not seem to work:
<code>WARNING: DEPRECATION: In order to remove global variable naming conflicts, Singularity's settings have been moved into the single `$singularity` variable. Please refer to our documentation (https://github.com/Team-Sass/Singularity/wiki) on how to update your settings. In the next version of Singularity, this warning will be removed. fixed has been returned.
  on line 37 of node_modules/singularitygs/stylesheets/singularitygs/helpers/_find.scss
  from line 14 of node_modules/singularitygs/stylesheets/singularitygs/gutter-styles/_find.scss
  from line 16 of node_modules/singularitygs/stylesheets/singularitygs/_api.scss
  from line 6 of sass/drupal_region/_left_sidebar.scss
  from line 66 of node_modules/breakpoint-sass/stylesheets/_breakpoint.scss
  from line 5 of sass/drupal_region/_left_sidebar.scss
</code>

The <code>_left_sidebar.scss</code> has includes there (@include breakpoint(), @include grid-span()).
I really didn't understand what @Snugug said, or what I must do. Can anybody help?
I am using the latest version (1.6.2) [npm install singularitygs].
Thanx.

**Comment by finteractive** [comment]
@Vaggos - Sungug reported there's a code deploy that should have fixed the issue.

If this is still a bug then the best way to report it is the re-create it on sassmeiser or codepen and show the bug happening. So remove ALL unrelated code and post up a gist like this...

http://www.sassmeister.com/gist/3d976fdb33a203fcb7e8

**Comment by Vagelis-Prokopiou** [comment]
Thanx @fosterinteractive. I will do that.
