### ISSUE TITLE
Full breakpoint values for responsive grids

### ISSUE THREAD

**Issue by pepelsbey** [at-import/Singularity#196]
I would like to use full Breakpoint syntax while defining responsive grid. Right now it’s possible to use either `min-width` or `max-width` MQ. With this approach it’s not possible to isolate some grid between breakpoints, it’s only possible to say “from this point and higher” or “from this point of lower” and overwrite values when needed. For example:

```
@include add-grid(2);
@include add-grid(3 at $palm);
@include add-grid(6 at $lap);
@include add-grid(12 at $desk);
```

By default it works this way:
- 2 everywhere
- overwrite to 3 if wider
- overwrite to 6 if wider
- overwrite to 12 if wider

I wish I could write it like this:

```
@include add-grid(2 at (max-width $palm));
@include add-grid(3 at ($palm $lap));
@include add-grid(6 at ($lap $desk));
@include add-grid(12 at $desk);
```
- 2 from 0 to $palm only
- 3 from $palm to $lap only
- 6 from $lap to $desk only
- 12 from $desk and higher

Why am I avoiding overwriting? Because I have the same principle in my code: it’s much easier to have style isolated between breakpoints and not to mess with the rest ones.

**Comment by pepelsbey** [comment]
And this would be perfectly backward-compatible any `at …` value could be easily passed to Breakpoints.

**Comment by pepelsbey** [comment]
I wonder if [breakpoint-slicer](https://github.com/lolmaus/breakpoint-slicer) would help me here

**Comment by lolmaus** [comment]
Singularity's grid definition is designed for that mobile first approach you described. Once your project demands a more sophisticated approach to grids and media queries, Singularity's grid definition becomes inappropriate.

Breakpoint Slicer does not address this issue.

I suggest that you abandon the grid definition and use `layout()` everywhere to set the grid in place. You can also use `reset-grid()` from [Singularity Quick Spanner](https://github.com/lolmaus/singularity-quick-spanner) to do the same without introducing a level of indentation.

Susy uses an interesting approach of combining both `layout()` and `breakpoint()` in one mixin. I'm considering adding it to SQS but i wonder what you guys say.

**Comment by pepelsbey** [comment]
But you haven’t replied my main question: why not use full breakpoint syntax?

I even tried this:

```
@include breakpoint($up-to-palm) {
    @include add-grid(2);
    }
@include breakpoint($palm-to-lap) {
    @include add-grid(3);
    }
@include breakpoint($lap-to-desk) {
    @include add-grid(6);
    }
@include breakpoint($desk-and-up) {
    @include add-grid(12);
    }
```

…but got some jumping mess in output CSS.

**Comment by lolmaus** [comment]
> But you haven’t replied my main question: why not use full breakpoint syntax?

This question should be answered by Singularity authors, and i'm merely a user.

> I even tried this...

I've written a detailed explanation why this approach makes no sense [here](http://stackoverflow.com/questions/24886511/singularity-responsive-gutter-widths/).

**Comment by pepelsbey** [comment]
> This question should be answered by Singularity authors, and i'm merely a user

Since you’re trying to explain me some Singularity principles I’m asking you. You have much more experience with this library anyway.

> I've written a detailed explanation why this approach makes no sense here

It was rather the very last attempt to solve this problem.

A bit unrelated: it seems like Susy doesn’t support fluid columns with fixed gutters, am I right?

**Comment by Snugug** [comment]
We've discussed what you are talking about when we first built the global grid context, and unfortunately what you're asking for cannot be done reliably due to a fallacy in understanding of how the system works. Let me explain:

Sass is not CSS, specifically, it's not run-time CSS. It cannot know what browser size you're in, it can, at best, give you an indication of what you say you're looking for. And this is precisely what Breakpoint context does; it tells us what media query you say you're in. Knowing what media query you're in (and what that mq's min-width is) and the list of min-widths you'd like to adopt a new context, we're able to determine what context to use. But this only work for the same query type of the same parameter (i.e. min-width _or_ max-width). Take, for instance, the following context issue:

``` scss
@include add-grid(5 at (min-width: 500px));
@include add-grid(7 at (max-width: 900px));

.problem {
  @include breakpoint((min-width: 700px)) {
    @include grid-span(1, 5);
  }
}
```

In that scenario, what grid should I use for `.problem`? It's larger than 500px but also smaller than 900px. We've got competing contexts that we cannot resolve. Same holds true for fenced queries; what if we've got a fenced query `500px 900px` but also have a context at `700px`? What context should I use?

As for your second comment, wrapping `add-grid` inside of a `breakpoint` call, it's something that we could support in theory, but it comes with its own set of mental hurdles. For instance, that grid definition isn't constrained to just that `breakpoint` call, it would be added to the global context, and would only work if all of the above conditions were met. As @lolmaus said, that's what the `@layout` mixin is for, for using a specific set of parameters for a block.

The idea of combining the ability to use `@layout` with a breakpoint is interesting, maybe something like the following:

``` scss
@mixin layout-at($layout, $breakpoint) {
  @include breakpoint($breakpoint) {
    @include layout($layout) {
      @content;
    }
  }
}
```

Thoughts on that? I think the I would have $layout be a map of options to make it easier to work with.

**Comment by pepelsbey** [comment]
@Snugug, thank you for detailed explanation. I tried this `layout-at` mixin instead of global `add-grid(X at N)` and it works great for me. So it would be good to have such helper available but not just available, but with proper use cases explained in documentation.

**Comment by Snugug** [comment]
I'll add it to the roadmap.

**Comment by pepelsbey** [comment]
That’s how I generate visual grid for my layout (without global grid defined), just for example:

``` scss
// Columns

$layouts: (
    2: $up-to-palm,
    3: $palm-to-lap,
    6: $lap-to-desk,
    12: $desk-and-up
);

@each $columns in map_keys($layouts) {
    @include layout-at($columns, map_get($layouts, $columns)) {
        @for $column from 1 through $columns {
            div:nth-child(#{$column}) {
                @include grid-span(1, $column);
                }
            }
        }
    }
```
