### ISSUE TITLE
Gem version compatibility and documentation

### ISSUE THREAD

**Issue by malthemilthers** [at-import/Singularity#201]
Hi,

I have a project that uses Singularity for its grids, and my build system completely broke when I updated to 1.4.0 for a different project. This is mainly my own fault as i wasn't running my compiling through bundle exec, as you state in your wiki. However, your wiki is not updated to use the new 1.4.0 version, and so i have a hard time making it work. I updated from the old gutter and grid syntax to the new mixin based syntax, and ran my compilation with bundle exec, but im still getting all sorts of weird errors. I figured that bundler would use the correct versions automatically, but we still have to include sass and compass in our gemfile, however we dont need to include breakpoint? 

I am very confused about what versions work with what, and i can't really figure it out from the documentation. if i want to use 1.4.0, what should my gem file look like? The docs are still using 1.2.x in the example. 

Also before I updated I only had to import singularitygs into my scss files, but now i have to include compass and breakpoint for it to work as well. Is this normal behaviour for the newer version, or is something in my setup wrong? 

Any explanation about version compatibility and how to make sure the dependency doesn't break would be very helpful - and an updated wiki would be nice too.

**Comment by Snugug** [comment]
All of the documentation (except, it seems, the installation documentation) has been updated by @iamcarrico to include the Singularity 1.2+ syntax. The syntax hasn't changed since 1.2.x. To see a full list of user-facing changes in 1.2+, see the [Changelog](https://github.com/at-import/Singularity/blob/1.x.x/CHANGELOG.md). If you've changed all of your add-grid/add-gutter/settings to the new mixins from the previous global variables, nothing else needed to change and Singularity should have continued working normally.

When you upgraded to Singularity 1.4 and moved to Bundler, you most likely moved to Sass 3.3+ which had some backwards-incompatible changes itself, specifically around scoping of variables (why we had to move from variables to mixins) that threw errors. Without you providing the errors you're still getting, I do not know for sure, but [here is the Sass CHANGELOG](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#330_7_march_2014)

**Comment by malthemilthers** [comment]
Okay, thank you - Could you explain what the updated installation gem file would look like with 1.4.0 ? And should it be necessary to require and import breakpoint and compass separately? 

Just so that i have a benchmark of what is "normal" behaviour, while I try and debug this.

Thank you for getting back to me quickly with very helpful info.

**Comment by Snugug** [comment]
The Gemfile is in the [installation instructions](https://github.com/at-import/Singularity/wiki/Installation#installation)

You need to import Breakpoint and Compass separately.

**Comment by malthemilthers** [comment]
Amazing. Thank you for updating!
