### ISSUE TITLE
Applying grid-span to multiple elements

### ISSUE THREAD

**Issue by lmartins** [at-import/Singularity#48]
Not a bug, just a question. 
When you have something like, for instance:

<section id="featured">
     <article>1</article>
     <article>2/article>
     <article>3/article>
</section>

How can you apply the grid-span at once for the three elements?
If I try  @include grid-span(1);  so that each article span one column i get the following error:

error main.scss (Line 140: Mixin grid-span is missing argument $location.)

I know what location is, but to explicitly apply it i would need to target each article individually which is not the goal here.

Just wanted to know if theres anyway to do this.

This is an exciting project and thank you for sharing it.

**Comment by Snugug** [comment]
So the issue with doing this is that the standard use case for Singularity is asymmetric grids and because of that, we require a position in the grid as well to know what sized column you're looking for. To implement this, we would need to write an entirely new grid system to support the different kind of thinking required to do this.

**Comment by lmartins** [comment]
Got it, thanks for clarifying.

**Comment by micahgodbolt** [comment]
@Snugug it looks like we'll need to update the "Use" section of singularity.gs. It states that "If no location is set this mixin will count through the columns for you. So if you have a 9 column grid and three mixins spanning 3 columns, the mixin will know what columns you are as well as know you reached the end of a row."

**Comment by Snugug** [comment]
That site as a whole needs to be updated.
