### ISSUE TITLE
non-horizontal grid features

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#55]
Before 1.0, any features like vertical rhythm, vertical grid (+ modular grid), skewed grids … ?

**Comment by Snugug** [comment]
I think vertical rhythm is a must (just found a weird bug where if you import compass after setting font scaling w/Singularity things break and I'm sad, but it's due to the way !default works, not what we've actually done) because the default Compass stuff simply doesn't work w/the font stuff that's programed in, but I think we can leave Vertical Grid and Skewed Grids for a later release. Let's only ship what's absolutely necessary for a 1.0.

Actually, IMO, we may not even need a configurable VR quite yet, just hard code it in for the time being then get back to it.

**Comment by scottkellum** [comment]
Cool, I agree with this. Get what exists solid first.

**Comment by VinSpee** [comment]
@Snugug can you elaborate on this vertical rhythm issue? I am experiencing some issues where setting +trailer() on a container is causing the grid to not be generated in output.
