### ISSUE TITLE
grid-span mixin stops working when using Compass' box-shadow mixin on a container

### ISSUE THREAD

**Issue by since1976** [at-import/Singularity#98]
I was setting up some grids and came across—what I believe—is a bug. 

When you use Compass' `box-shadow` mixin on a container—which is declared before any Singularity `grid-span`'s in the source order of your scss file—no values from the `grid-span` are generated to the resulting stylesheet. If you move that block below your singularity layout styles everything works as advertised. 

I have created a [GitHub](https://github.com/since1976/sigulartybugtest) repo with some test files that should show what is happening. Just comment out the different `.main` blocks in the base.scss stylesheet.

**Comment by Snugug** [comment]
Very interesting, I've never heard or come across something like this. Will look into it.

UPDATE:
With a reduced example describing the exact circumstances you've described, it works as expected. When bringing your supplied code into a sample file and running it through the current version of Singularity (`1.0.8`), it likewise works as expected.

I'm not entirely sure what to tell you, it being a case of "works for me". Make sure your Singularity version is up to date, or if this is a smaller example from a larger project, look through that project to see if there are differences between the supplied example Sass and your Sass. Truth be told, Singularity has absolutely 0 interaction with `box-shadow` and, even more than that, each `grid-span` is designed to have absolutely no interaction with even any `grid-span` mixin around it, so I'm not entirely sure where the issue is coming from for you.

**Comment by since1976** [comment]
I extracted that code from a larger project but it is a pretty barebones test, 1 file with only a couple of singularity rules applied and nothing else. 

Pretty sure I am running 1.0.8. I just did a `gem list singularitygs` and 1.0.8 is the first that shows.

```
*** LOCAL GEMS ***
singularitygs (1.0.8, 1.0.4, 1.0.alpha.2, 1.0.alpha.1, 1.0.alpha.0, 0.0.17)
```

Could it have to do with the version of compass I'm using?

```
compass version
Compass 0.13.alpha.4 (Markab)
```

**Comment by since1976** [comment]
Must have been a conflict with either a version of compass or singularity. I uninstalled all versions of both and then installed fresh versions and everything is now working fine.

Certainly a weird thing to happen though, and one that took me quite a few hours to debug.

Thanks for your help and perspective.

**Comment by timkelty** [comment]
Just ran into this same issue.

Uninstalling/reinstalling gems did not fix for me, though.
Any ideas?
Running with:

```
  gem "compass", "~> 0.13.alpha.4"
  gem "singularitygs", "~> 1.1.2"
```

**Comment by Snugug** [comment]
There is a known incompatibility with Compass 0.13. Once Compass 0.13 is compatible with Sass 3.3, we will be updating Singularity and resolving this issue

**Comment by timkelty** [comment]
Thanks.

For the time being changing my gemfile to this seems to fix it:

```
  gem "compass",
    :git => "https://github.com/chriseppstein/compass.git",
    :branch => "stable"
```
