### ISSUE TITLE
Firefox Aurora doesn't show debug grid backgrounds

### ISSUE THREAD

**Issue by lmartins** [at-import/Singularity#99]
Hi,

Im using Firefox Aurora to test a responsive grid, it doesn't show the background grid, while webkit browser do. Reading the wiki it seems Firefox should support it. 

Thanks.

**Comment by scottkellum** [comment]
Can’t replicate here. Seems to work fine.

```
.ag2 {
  @include background-grid(6);
  @include grid-span(6);
}
```

![GitHub Logo](http://img.pgdn.us/grid-firefox.png)

**Comment by scottkellum** [comment]
Ah, you mean the js version. hopefully @Snugug can comment more.

**Comment by lmartins** [comment]
Hi @scottkellum 
No, I was referring to the css version. 

That's really weird. Just to be sure i've tried again and still the same behavior. Shows just fine on Chrome but no sign of it on Firefox.

It's not a major thing to me as I use Chrome for developing, just wanted you to know. Perhaps something related to my setup.

**Comment by Snugug** [comment]
I'm going to close this issue. I have been working extensively with Firefox and our background grids work in stable Firefox as expected. Additionally, since this was filed, there have been 1 or 2 versions of Firefox to be released (hard to tell, only relative dates in the comments), and they continue to work. I'll see if I can recreate your error in the current version of Aurora, but as that is an experimental browser and it works fine in the current stable versions, I do not believe this is something we need to keep open. Experimental browsers are by definition not stable and therefore unpredictable.
